name: Sync Secrets to Azure KeyVault #RO

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: kube-deploy
    defaults:
      run:
        shell: bash
    container:
      image: mck-tech-platform-srvs.jfrog.io/kubectl-azure:latest
      credentials:
        username: ${{ secrets.DEV_PORTAL_JFROG_USERNAME }}
        password: ${{ secrets.DEV_PORTAL_JFROG_API_KEY }}
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_KEYVAULT }}
      - name: Set secrets from GH to vault
        env:
          VT: vt-developer-portal
        run: |
            az keyvault secret set --vault-name $VT --name "AUTH-GITHUB-CLIENT-ID-AZURE" --value "${{ secrets.AUTH_GITHUB_CLIENT_ID_AZURE }}"
            az keyvault secret set --vault-name $VT --name "AUTH-GITHUB-CLIENT-ID-AZURE-DEV" --value "${{ secrets.AUTH_GITHUB_CLIENT_ID_AZURE_DEV }}"
            az keyvault secret set --vault-name $VT --name "AUTH-GITHUB-CLIENT-SECRET-AZURE" --value "${{ secrets.AUTH_GITHUB_CLIENT_SECRET_AZURE }}"
            az keyvault secret set --vault-name $VT --name "AUTH-GITHUB-CLIENT-SECRET-AZURE-DEV" --value "${{ secrets.AUTH_GITHUB_CLIENT_SECRET_AZURE_DEV }}"
            az keyvault secret set --vault-name $VT --name "AZURE-CREDENTIALS" --value "${{ secrets.AZURE_CREDENTIALS }}"
            az keyvault secret set --vault-name $VT --name "VERACODE-API-ID" --value "${{ secrets.VERACODE_API_ID }}"
            az keyvault secret set --vault-name $VT --name "VERACODE-API-KEY" --value "${{ secrets.VERACODE_API_KEY }}"
          
  save-dev-secrets:
    environment: dev
    runs-on: kube-deploy
    defaults:
      run:
        shell: bash
    container:
      image: mck-tech-platform-srvs.jfrog.io/kubectl-azure:latest
      credentials:
        username: ${{ secrets.DEV_PORTAL_JFROG_USERNAME }}
        password: ${{ secrets.DEV_PORTAL_JFROG_API_KEY }}
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_KEYVAULT }}
      - name: Set secrets from GH to vault
        env:
          VT: vt-developer-portal
        run: |
            az keyvault secret set --vault-name $VT --name "DEVENV-AUTH-OKTA-CLIENT-ID" --value "${{ secrets.AUTH_OKTA_CLIENT_ID }}"
            az keyvault secret set --vault-name $VT --name "DEVENV-AUTH-OKTA-CLIENT-SECRET" --value "${{ secrets.AUTH_OKTA_CLIENT_SECRET }}"
            az keyvault secret set --vault-name $VT --name "DEVENV-AUTH-OKTA-CLIENT-URL" --value "${{ secrets.AUTH_OKTA_CLIENT_URL }}"
            az keyvault secret set --vault-name $VT --name "DEVENV-BACKSTAGE-DB-AKS-DEV-PASS" --value "${{ secrets.BACKSTAGE_DB_AKS_DEV_PASS }}"
            az keyvault secret set --vault-name $VT --name "DEVENV-BACKSTAGE-DB-AKS-DEV-USER" --value "${{ secrets.BACKSTAGE_DB_AKS_DEV_USER }}"
            az keyvault secret set --vault-name $VT --name "DEVENV-BACKSTAGE-DB-HOST" --value "${{ secrets.BACKSTAGE_DB_HOST }}"
            az keyvault secret set --vault-name $VT --name "DEVENV-BACKSTAGE-DB-PASS" --value "${{ secrets.BACKSTAGE_DB_PASS }}"
            az keyvault secret set --vault-name $VT --name "DEVENV-BACKSTAGE-DB-USER" --value "${{ secrets.BACKSTAGE_DB_USER }}"
            az keyvault secret set --vault-name $VT --name "DEVENV-DEV-PORTAL-KUBE-SA-US" --value "${{ secrets.DEV_PORTAL_KUBE_SA_US }}"
          
  save-prod-secrets:
    environment: prod
    runs-on: kube-deploy
    defaults:
      run:
        shell: bash
    container:
      image: mck-tech-platform-srvs.jfrog.io/kubectl-azure:latest
      credentials:
        username: ${{ secrets.DEV_PORTAL_JFROG_USERNAME }}
        password: ${{ secrets.DEV_PORTAL_JFROG_API_KEY }}
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_KEYVAULT }}
      - name: Set secrets from GH to vault
        env:
          VT: vt-developer-portal
        run: |
            az keyvault secret set --vault-name $VT --name "PRODENV-BACKSTAGE-DB-AKS-PASS" --value "${{ secrets.BACKSTAGE_DB_AKS_PASS }}"
            az keyvault secret set --vault-name $VT --name "PRODENV-BACKSTAGE-DB-AKS-USER" --value "${{ secrets.BACKSTAGE_DB_AKS_USER }}"
            az keyvault secret set --vault-name $VT --name "PRODENV-BACKSTAGE-DB-HOST" --value "${{ secrets.BACKSTAGE_DB_HOST }}"
            az keyvault secret set --vault-name $VT --name "PRODENV-BACKSTAGE-DB-PASS" --value "${{ secrets.BACKSTAGE_DB_PASS }}"
            az keyvault secret set --vault-name $VT --name "PRODENV-BACKSTAGE-DB-USER" --value "${{ secrets.BACKSTAGE_DB_USER }}"
            az keyvault secret set --vault-name $VT --name "PRODENV-PORTAL-KUBE-SA-US" --value "${{ secrets.PORTAL_KUBE_SA_US }}"
